{
    'bunny_class'             => 'Foo::Bunny',
    'gc_threshold'            => 456,
    'logger'                  => '/dev/zero',
    'loglayout'               => 'FOO: %m%n',
    'loglevel'                => 'WARN',
    'mq_class'                => 'Foo::AMQP',
    'password'                => 'secret123',
    'redis_db'                => 2,
    'redis_hosts'             => 'somehost:123',
    'servers'                 => 'otherhost:456',
    'redis_operation_retries' => '456',
    'user'                    => 'admin',
    'verbose'                 => 1,
    'vhost'                   => '/bar',
}
